# These are supported funding model platforms

patreon: 3urobeat
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VAVVKE4L962H6&source=url # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
