# These are supported funding model platforms

patreon: 3urobeat
custom: ["paypal.me/3urobeat", "blockchain.com/btc/address/18cEFztHAGfRGBEfGQKBJ2huQWpjrgv95A"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
